# Generated by Django 2.1.3 on 2019-02-22 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(null=True)),
                ('tname', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3452, verbose_name='标题')),
                ('aid', models.IntegerField()),
                ('view', models.IntegerField(null=True, verbose_name='播放量')),
                ('danmaku', models.IntegerField(null=True, verbose_name='弹幕数')),
                ('favourit', models.IntegerField(null=True)),
                ('coin', models.IntegerField(null=True, verbose_name='硬币')),
                ('like', models.IntegerField(null=True, verbose_name='点赞')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.Author')),
                ('tag', models.ManyToManyField(to='showdata.Tag')),
            ],
        ),
    ]
