# Generated by Django 2.1.3 on 2019-02-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.AlterField(
            model_name='video',
            name='aid',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
