# Generated by Django 2.1.3 on 2019-02-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0003_auto_20190223_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='view',
            new_name='views',
        ),
    ]
